# Generated by Django 3.2.4 on 2021-06-23 08:40

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210623_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post_default_image.jpg', null=True, upload_to=post.models.upload_image),
        ),
    ]
