# Generated by Django 3.2.4 on 2021-06-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='action',
            new_name='active',
        ),
    ]
