# Generated by Django 3.2.4 on 2021-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20210623_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(blank=True, default=1, editable=False, null=True),
        ),
    ]
