# Generated by Django 3.2.4 on 2021-06-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20210624_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='actuve',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True),
        ),
    ]
