# Generated by Django 3.2.4 on 2021-06-30 13:27

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_rename_actuve_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.upload_image),
        ),
    ]
