# Generated by Django 3.2.4 on 2021-07-02 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20210702_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('active', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='PostLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(max_length=4000, verbose_name='content')),
                ('active', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='active')),
                ('categories', models.ManyToManyField(blank=True, to='post.Category', verbose_name='categories')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='post.language', verbose_name='language')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_lang', to='post.post', verbose_name='post')),
            ],
        ),
    ]
