# Generated by Django 3.2.4 on 2021-07-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_language_postlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='post.language', verbose_name='language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_lan', to='post.language', verbose_name='language'),
        ),
    ]
